#!/usr/bin/env bash
echo "= create bucket"


# Usage check
if [ $# -eq 0 ]; then
  echo "Usage: $0 <bucket-name>"
  exit 1
fi

BUCKET_NAME="$1"
REGION="us-east-1"  # Change this if using a different region


aws s3api create-bucket --bucket "$BUCKET_NAME" --region "$REGION"