#! /usr/bin/env bash

echo "=list objects"

if [ $# -eq 0 ]; then
  echo "Usage: $0 <bucket-name>"
  exit 1
fi

BUCKET_NAME="$1"
REGION="us-east-1"  # Change this if using a different region


aws s3api list-objects-v2 --bucket "$BUCKET_NAME" 
