#!/usr/bin/env bash
echo "== Sync"
set -e

if [ $# -eq 0 ]; then
  echo "Usage: $0 <bucket-name>"
  exit 1
fi


#check for filename prefix
if [ $# -eq 0 ]; then
  echo "Usage: $0 <bucket-name>"
  exit 2
fi

BUCKET_NAME="$1"
FILENAME_PREFIX="$2"

# Set output directory
OUTPUT_DIR="/tmp/s3-bash-scripts"

rm -r $OUTPUT_DIR

mkdir -p "$OUTPUT_DIR"

NUM_FILES=$((RANDOM % 6 + 5))
# Create 5 random files with random names and content
for ((i=1; i<=$NUM_FILES; i++)); do

    FILENAME="$OUTPUT_DIR/${FILENAME_PREFIX}_$i.txt"

    dd if=/dev/urandom of="$FILENAME" bs=1024 count=$((RANDOM % 1024 + 1)) 2>/dev/null
done



tree $OUTPUT_DIR

aws s3 sync $OUTPUT_DIR s3://$BUCKET_NAME/files